(ns scicloj.metamorph.ml.design-matrix
  (:require
   [clojure.set :as set]
   [clojure.walk :as cljwalk]
   [tablecloth.api :as tc]
   [tech.v3.dataset :as ds]
   [tech.v3.dataset.column-filters :as cf]
   [tech.v3.dataset.modelling :as ds-mod]))

(defn- create-design-matrix-column [ds new-column spec]
  (let [new-column (if (nil? new-column)
                     (str spec)
                     new-column)

        cols (filterv
              #(tc/has-column? ds %)

              (distinct
               (concat (flatten spec)
                       (when (map? spec)
                         (flatten
                          (vals spec))))))


        syms
        (mapv
         (fn [col] {:sym (gensym)
                    :col col})
         cols)

        col-sym-m (zipmap  (mapv :col syms)
                           (mapv :sym syms))

        fnn
        (list 'fn (mapv :sym syms)
              (cljwalk/postwalk-replace col-sym-m spec))
        f (eval fnn)]

    (tc/map-columns ds new-column cols f)))



(defn- expand-keyword-to-identity [col-spec]
  (if (keyword? col-spec)
    (vector col-spec (list  'clojure.core/identity col-spec))
    col-spec))

(defn create-design-matrix
  "Converts the given dataset into a full numeric dataset.
   
   * `ds` is the tech.v3.dataset to transform
   * `target-specs` are the specifications how to transform the target variables
   * `features-specs` are the specifications how to transform the features 

   The 'spec' can express several types of dataset transformations in a compact way:
   - add new derived columns
   - remove columns
   - rename columns
   - convert columns to categorical
   - set inference target


   Columns specs are in general given as pairs of [colname function]
   
   function need to be given as list (quoted by '), and can refer to column names.

   They get evaluated from top->bottom, and can refer to each other.

   Not listed columns get removed.

   Special syntax:

   - :a-column                      keeps column as-is (calls `identity` fn)
   - [nil '(+ a b)] or ['(+ a b)]   autogenerated column name 
   
   The following aliases can be used as part of the spec.
   (Other functions need to be full qualified).

   clojure.core  can be used without full qualifying the symbols

   - ds             (tech.v3.dataset)
   - tc             (tablecloth.api)
   - tcc            (tablecloth.column.api)
   

   Example:
 
   (dm/create-design-matrix
         ds
         [:y] 
         [         
          [:sum '(+ :a :b :c)]
         ])
   
   This will:
   - set inference target to y:
   - create a new derived variables :sum, being the sum of a,b,c
   - remove all columns except :y and :sum
   
   This covers a range of cases, but is not as complete as `R formulae`.
   Specialy it does not handle automatic expansion of categorical variables,
   but these can be manually specified.
   

   See  `design_matrix_test.clj` for more examples.

   (for model type :fastmath/ols , linear regression, we support a different way
   of expressing arbitrary 'row transformations' using :transformer option 
   see `fastmath.ml/lm` documentation)
   
   "
  [ds
   targets-specs
   features-specs]

  ;; be sure, they are available
  (require '[tech.v3.dataset :as ds]
           '[tablecloth.api :as tc]
           '[tablecloth.column.api :as tcc])

  (let [enhanced-features-specs
        (map expand-keyword-to-identity features-specs)
        ds-columns (tc/column-names ds)

        mapping-specs-cols
        (concat targets-specs
                (->> enhanced-features-specs
                     (map first)
                     (remove nil?)))

        columns-to-be-removed
        (set/difference (into #{} ds-columns)
                        (into #{} mapping-specs-cols))


        transformed-ds
        (reduce
         (fn [ds col-spec-list]
           (let [[new-col col-spec]  (if (= 2 (count col-spec-list))
                                       [(first col-spec-list) (second col-spec-list)]
                                       [nil (first col-spec-list)])]


             (create-design-matrix-column ds new-col col-spec)))
         ds
         enhanced-features-specs)

        all-cols (tc/column-names transformed-ds)


        seperated-ds
        (reduce
         (fn [ds col]
           (let [new-ds (if  (-> (get ds col) first sequential?)
                          (tc/array-column->columns ds col {:prefix col})
                          ds)
                 new-ds (if  (-> (get ds col) first map?)
                          (tc/map-column->columns ds col)
                          new-ds)]
             new-ds))
         transformed-ds
         all-cols)]


    (-> seperated-ds
        (ds-mod/set-inference-target targets-specs)
        (tc/drop-columns columns-to-be-removed)
        (ds/categorical->number cf/categorical))))



