(ns scicloj.metamorph.design-matrix-test
  (:require  [clojure.test :as t]
             [tablecloth.api :as tc]
             [tablecloth.column.api :as tcc]
             [tech.v3.dataset.tensor :as tensor]
             [scicloj.metamorph.ml.design-matrix :as dm]))


(defn interactions [a b]
  (vector (tcc/* a b)
          (tcc/+ a b)))

(->
 (tc/dataset

  {"a" [7 3 2 3 4 5 6 7 8]              ;will be removed from dm
   :b [1 2 3 2 3 4 3 2 1]               ;stays as is
   'c [3 1 2 4 2 1 3 2 4]               ;will be remove from ds
   :x ["a" "b" "c" "d" "e" "f" "g" "h" "i"]
   :y [3 1 2 4 2 1 3 2 4]})



 (dm/create-design-matrix
  [:y]                                  ;becomes "target column"
  [
   [:sum '(+ a b c)]
   [:b '(identity b)]                   ; stays as is
   [:a** '(tcc/pow a 2)]
   [:a-str '(str a)]
   [nil '(clojure.string/upper-case (str x a))] ;autogenerated colum name
   [:a+c '(+ a c)]
   [:a+c*b '(* a+c b)]
   [:interaction '(interactions b c)] ;will be split, as it returns seq in mapping,
   [nil '(tcc/+ a b c sum a+c a+c*b)]]) ;; all still non numeric are get converted and become numerica
 (tensor/dataset->tensor))
;; => #tech.v3.tensor<float64>[9 11]
;;    [[1.000 3.000 11.00 49.00 5.000 1.000 10.00 10.00 42.00 3.000 4.000]
;;     [2.000 1.000 6.000 9.000 1.000 0.000 4.000 8.000 24.00 2.000 3.000]
;;     [3.000 2.000 7.000 4.000 0.000 2.000 4.000 12.00 30.00 6.000 5.000]
;;     [2.000 4.000 9.000 9.000 1.000 3.000 7.000 14.00 39.00 8.000 6.000]
;;     [3.000 2.000 9.000 16.00 2.000 4.000 6.000 18.00 42.00 6.000 5.000]
;;     [4.000 1.000 10.00 25.00 3.000 5.000 6.000 24.00 50.00 4.000 5.000]
;;     [3.000 3.000 12.00 36.00 4.000 6.000 9.000 27.00 60.00 9.000 6.000]
;;     [2.000 2.000 11.00 49.00 5.000 7.000 9.000 18.00 49.00 4.000 4.000]
;;     [1.000 4.000 13.00 64.00 6.000 8.000 12.00 12.00 50.00 4.000 5.000]]


;; before teh dataset looks like thsiq

 ;; => _unnamed [9 10]:
 ;;    | :b | :sum | :a** | :a-str | (clojure.string/upper-case (str x a)) | :a+c | :a+c*b | (tcc/+ a b c sum a+c a+c*b) | :interaction-0 | :interaction-1 |
 ;;    |---:|-----:|-----:|--------|---------------------------------------|-----:|-------:|----------------------------:|---------------:|---------------:|
 ;;    |  1 |   11 | 49.0 |      7 |                                    A7 |   10 |     10 |                          42 |              4 |              3 |
 ;;    |  2 |    6 |  9.0 |      3 |                                    B3 |    4 |      8 |                          24 |              3 |              2 |
 ;;    |  3 |    7 |  4.0 |      2 |                                    C2 |    4 |     12 |                          30 |              5 |              6 |
 ;;    |  2 |    9 |  9.0 |      3 |                                    D3 |    7 |     14 |                          39 |              6 |              8 |
 ;;    |  3 |    9 | 16.0 |      4 |                                    E4 |    6 |     18 |                          42 |              5 |              6 |
 ;;    |  4 |   10 | 25.0 |      5 |                                    F5 |    6 |     24 |                          50 |              5 |              4 |
 ;;    |  3 |   12 | 36.0 |      6 |                                    G6 |    9 |     27 |                          60 |              6 |              9 |
 ;;    |  2 |   11 | 49.0 |      7 |                                    H7 |    9 |     18 |                          49 |              4 |              4 |
 ;;    |  1 |   13 | 64.0 |      8 |                                    I8 |   12 |     12 |                          50 |              5 |              4 |
