(ns scicloj.metamorph.design-matrix-test
  (:require  [clojure.test :as t]
             [tablecloth.api :as tc]
             [tech.v3.dataset.tensor :as tensor]

             [scicloj.metamorph.ml.design-matrix :as dm]))

(->
 (tc/dataset

  {"a" [7 3 2 3 4 5 6 7 8]              ;will be removed from dm
   :b [1 2 3 2 3 4 3 2 1]               ;stays as is
   'c [3 1 2 4 2 1 3 2 4]               ;will be remove from ds
   :x ["a" "b" "c" "d" "e" "f" "g" "h" "i"]
   :y [3 1 2 4 2 1 3 2 4]})


 (->
  (dm/create-design-matrix
   [:y]                                 ;becomes "target column"
   [
    [:sum '(+ a b c)]
    [:b '(identity b)]                  ; stays as is
    [:a** '(tcc/pow a 2)]
    [:a-str '(str a)]]
   [nil '(clojure.string/upper-case (str x a)) ;autogenerated colum name
    [:a+c '(+ a c)]
    [:a+c*b '(* a+c b)]
    [:interaction '(dm/interactions b c)] ;will be split, as it returns seq in mapping,
    [nil '(tcc/+ a b c sum a+c a+c*b)]]))
 ;; all non numeric get numeric automatic
 (tensor/dataset->tensor))




;; => _unnamed [9 10]:
;;    | :b | :sum | :a** | :a-str | (clojure.string/upper-case (str x a)) | :a+c | :a+c*b | (tcc/+ a b c sum a+c a+c*b) | :interaction-0 | :interaction-1 |
;;    |---:|-----:|-----:|--------|---------------------------------------|-----:|-------:|----------------------------:|---------------:|---------------:|
;;    |  1 |   11 | 49.0 |      7 |                                    A7 |   10 |     10 |                          42 |              4 |              3 |
;;    |  2 |    6 |  9.0 |      3 |                                    B3 |    4 |      8 |                          24 |              3 |              2 |
;;    |  3 |    7 |  4.0 |      2 |                                    C2 |    4 |     12 |                          30 |              5 |              6 |
;;    |  2 |    9 |  9.0 |      3 |                                    D3 |    7 |     14 |                          39 |              6 |              8 |
;;    |  3 |    9 | 16.0 |      4 |                                    E4 |    6 |     18 |                          42 |              5 |              6 |
;;    |  4 |   10 | 25.0 |      5 |                                    F5 |    6 |     24 |                          50 |              5 |              4 |
;;    |  3 |   12 | 36.0 |      6 |                                    G6 |    9 |     27 |                          60 |              6 |              9 |
;;    |  2 |   11 | 49.0 |      7 |                                    H7 |    9 |     18 |                          49 |              4 |              4 |
;;    |  1 |   13 | 64.0 |      8 |                                    I8 |   12 |     12 |                          50 |              5 |              4 |
