(ns scicloj.metamorph.design-matrix-test
  (:require
   [clojure.test :as t :refer [deftest is]]
   [fastmath.ml.regression :as regression]
   [scicloj.metamorph.common]
   [scicloj.metamorph.ml.design-matrix :as dm]
   [scicloj.metamorph.ml.rdatasets :as rdatasets]
   [tablecloth.api :as tc]
   [tablecloth.column.api]
   [tech.v3.dataset :as ds]
   [tech.v3.dataset.column-filters :as cf]
   [tech.v3.dataset.tensor :as tensor]))



(defn interactions [a b]
  (vector (tablecloth.column.api/* a b)
          (tablecloth.column.api/+ a b)))

(def ds
  (tc/dataset

   {"a" [7 3 2 3 4 5 6 7 8]              ;will be removed from dm
    "a1" [7 3 2 3 4 5 6 7 8]              ;will be removed from dm
    "a2" [7 3 2 3 4 5 6 7 8]              ;will be removed from dm
    :b [1 2 3 2 3 4 3 2 1]               ;stays as is
    'c [3 1 2 4 2 1 3 2 4]               ;will be remove from ds
    :x ["a" "b" "c" "d" "e" "f" "g" "h" "i"]
    :y [3 1 2 4 2 1 3 2 4]}))

(deftest design-matrix
  (let [my-dm

        (dm/create-design-matrix
         ds
         [:y]                                  ;becomes "target column"
         [[:sum '(+ "a" :b c)]
          [:b '(clojure.core/identity :b)]                   ; stays as is
          [:a** '(tablecloth.column.api/pow "a" 2)]
          [:a-str '(clojure.core/str "a")]
          [nil '(clojure.string/upper-case (str :x "a1"))] ;autogenerated colum name
          ['(clojure.string/upper-case (str :x "a2"))] ;autogenerated colum name
          [:a+c '(clojure.core/+ "a" c)]
          ['a+c*b '(clojure.core/* :a+c :b)]
          [:interaction '(scicloj.metamorph.design-matrix-test/interactions :b c)] ;will be split, as it returns seq in mapping,
          [nil '(tablecloth.column.api/+ "a" :b c :sum :a+c a+c*b)]])

        t (tensor/dataset->tensor my-dm)]

    (is (=

         [:b
          :y
          :sum
          :a**
          :a-str
          "(clojure.string/upper-case (str :x \"a1\"))"
          "(clojure.string/upper-case (str :x \"a2\"))"
          :a+c
          'a+c*b
          "(tablecloth.column.api/+ \"a\" :b c :sum :a+c a+c*b)"
          :interaction-0
          :interaction-1]
         (tc/column-names my-dm)))

    (is (=
         [[1.000 3.000 11.00 49.00 5.000 1.000 1.000 10.00 10.00 42.00 3.000 4.000]
          [2.000 1.000 6.000 9.000 1.000 0.000 0.000 4.000 8.000 24.00 2.000 3.000]
          [3.000 2.000 7.000 4.000 0.000 2.000 2.000 4.000 12.00 30.00 6.000 5.000]
          [2.000 4.000 9.000 9.000 1.000 3.000 3.000 7.000 14.00 39.00 8.000 6.000]
          [3.000 2.000 9.000 16.00 2.000 4.000 4.000 6.000 18.00 42.00 6.000 5.000]
          [4.000 1.000 10.00 25.00 3.000 5.000 5.000 6.000 24.00 50.00 4.000 5.000]
          [3.000 3.000 12.00 36.00 4.000 6.000 6.000 9.000 27.00 60.00 9.000 6.000]
          [2.000 2.000 11.00 49.00 5.000 7.000 7.000 9.000 18.00 49.00 4.000 4.000]
          [1.000 4.000 13.00 64.00 6.000 8.000 8.000 12.00 12.00 50.00 4.000 5.000]]
         t))))


(deftest all-col-names-varints
  (let [ds
        (tc/dataset
         {:a [0 1 2]
          'a [2 3 4]
          "a" [4 5 6]
          :y [0 0 0]})
        dm
        (dm/create-design-matrix
         ds
         [:y]
         [[:sum '(clojure.core/+ :a a "a")]])]

    (is (= [6 9 12]
           (:sum dm)))))

(deftest dm-mutiple-returns
  (is (=
       [{:y 2, :p-0 2, :p-1 0, :q-a 2, :q-b 0, :r-0 2, :r-1 0}
        {:y 1, :p-0 2, :p-1 1, :q-a 2, :q-b 1, :r-0 2, :r-1 1}
        {:y 0, :p-0 2, :p-1 0, :q-a 2, :q-b 0, :r-0 2, :r-1 0}]

       (->
        (dm/create-design-matrix (tc/dataset {"v" [4 5 6]
                                              :w [:A :B :C]
                                              :x (range 3)
                                              :y (reverse (range 3))})
                                 [:y]
                                 [[:p '((juxt tablecloth.column.api/+ tablecloth.column.api/*) :x :y)]
                                  [:q '{:a (tablecloth.column.api/+ :x :y) :b (tablecloth.column.api/* :x :y)}]
                                  [:r '[(tablecloth.column.api/+ :x :y)
                                        (tcc/* :x :y)]]])
        (tc/rows :as-maps)))))



(deftest test-map-column->columns--keyword
  (is (= [:a-x :a-y]
         (tc/column-names
          (tc/map-column->columns
           (tc/dataset
            {:a [{:x 1 :y 2}
                 {:x 3 :y 4}]}) :a))))


  (is (= ["a-x" "a-y"]
         (tc/column-names
          (tc/map-column->columns
           (tc/dataset
            {"a" [{:x 1 :y 2}
                  {:x 3 :y 4}]}) "a"))))

  (is (= [:a-x :a-y]
         (tc/column-names
          (tc/map-column->columns
           (tc/dataset
            {:a [{:x 1 "y" 2}
                 {:x 3 "y" 4}]}) :a)))))

(deftest auto-identity
  (is (=
       (:cyl (dm/create-design-matrix (rdatasets/datasets-mtcars)
                                      [:mpg]
                                      [[:cyl '(clojure.core/identity :cyl)]]))
       (:cyl
        (dm/create-design-matrix (rdatasets/datasets-mtcars)
                                 [:mpg]
                                 [:cyl])))))



(defn- lm [data target-specs feature-specs]
  (let [dm
        (dm/create-design-matrix data target-specs feature-specs)]
    (regression/lm
     (->
      (cf/target dm)
      (ds/columns)
      first
      vec)
     (->
      (cf/feature dm)
      (ds/rowvecs))
     {:intercept? true
      :names (vec 
              
              (ds/column-names (cf/feature dm))
              )})))
  
(deftest interactions-test

  (is (=
       [-10.731981967960817 5.360877730563882]
       ;lm(formula = prestige ~ education, data = Prestige)
       (->>
        (lm (rdatasets/carData-Prestige) [:prestige] [:education])
        :coefficients
        (map :estimate))))


  (is (=
       [-110.96582408762559 3.730507828371897 13.43822306488778 0.04689513774526512]
       (->>
        (lm (rdatasets/carData-Prestige)
            ;;lm(formula = prestige ~ education + log (income) + women, data = Prestige)
            [:prestige]
            [:education
             [:income '(tcc/log :income)]
             :women])
        :coefficients
        (map :estimate))))



  (let [prestige
        (->
         (rdatasets/carData-Prestige)
         (tc/drop-missing)
         (ds/categorical->one-hot [:type]))]
    (is (=
         [-81.20186676367538 3.2844857908366167 10.487471390281774 -1.4394028590407122 6.7508872629242]

         (->>
          (lm
           ;;lm(formula = prestige ~ education + log(income) + type, data = Prestige)
           prestige
           [:prestige]
           [:education
            [:income '(tcc/log :income)]
       ;:type-bc  ;; autodropped by R...this is because of dummy-contrasts
            :type-wc
            :type-prof])
          :coefficients
          (map :estimate))))

    (is (=
         {"(tcc/* :type-prof :education)" 0.6973988905060939,
          "(tcc/* :type-wc :education)" 3.6400383797567244,
          "Intercept" -120.04591326225307,
          "(tcc/* :type-prof :log-income)" -9.428817876039425,
          :type-prof 85.16012507441735,
          "(tcc/* :type-wc :log-income)" -8.155610127178688,
          :education 2.3356724126745942,
          :type-wc 30.241187147883345,
          :log-income 15.982481922371733}


         (->
          (lm
           prestige
           ;lm(prestige ~ type * (education + log (income)), data = carData::Prestige)
           [:prestige]
           [:type-prof
            :type-wc
            :education
            [:log-income '(tcc/log :income)]
            ['(tcc/* :type-prof :education)]
            ['(tcc/* :type-wc :education)]
            ;:type-bc removed in R
            ['(tcc/* :type-prof :log-income)]
            ['(tcc/* :type-wc :log-income)]])

          ((fn [res]
             (zipmap
              (:names res)
              (map :estimate (:coefficients res))))))))))

